{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 45,
   "id": "b4005f2e",
   "metadata": {},
   "outputs": [],
   "source": [
    "import tensorflow as tf\n",
    "from tensorflow.keras import datasets, layers, models\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 46,
   "id": "70b811e3",
   "metadata": {},
   "outputs": [],
   "source": [
    "(X_train, y_train), (X_test, y_test) = datasets.cifar10.load_data()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "id": "f1565fcf",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(10000, 32, 32, 3)"
      ]
     },
     "execution_count": 47,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "X_test.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 48,
   "id": "9c9ab01f",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(10000, 1)"
      ]
     },
     "execution_count": 48,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "y_test.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 49,
   "id": "37f31299",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[6],\n",
       "       [9],\n",
       "       [9],\n",
       "       [4],\n",
       "       [1]], dtype=uint8)"
      ]
     },
     "execution_count": 49,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "y_train[:5]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "id": "4d8934b8",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(array([6, 9, 9, ..., 9, 1, 1], dtype=uint8),\n",
       " array([3, 8, 8, ..., 5, 1, 7], dtype=uint8))"
      ]
     },
     "execution_count": 50,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "y_train = y_train.reshape(-1,)\n",
    "y_test = y_test.reshape(-1,)\n",
    "y_train, y_test"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 51,
   "id": "98766a88",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['airplane',\n",
       " 'automobile',\n",
       " 'bird',\n",
       " 'cat',\n",
       " 'deer',\n",
       " 'dog',\n",
       " 'frog',\n",
       " 'horse',\n",
       " 'ship',\n",
       " 'truck']"
      ]
     },
     "execution_count": 51,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "classes = [\"airplane\",\"automobile\",\"bird\",\"cat\",\"deer\",\"dog\",\"frog\",\"horse\",\"ship\",\"truck\"]\n",
    "classes"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 52,
   "id": "d7b795d3",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<matplotlib.image.AxesImage at 0x291beaaf0>"
      ]
     },
     "execution_count": 52,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAMkAAADICAYAAABCmsWgAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjcuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/bCgiHAAAACXBIWXMAAA9hAAAPYQGoP6dpAAAcXUlEQVR4nO2dbWwU57XH/zP7vvburF/wGsd24wQaCBTSUCBWeqOUuqFINw0BXaVfbmmb2yipjQR8qOqqTaSolav2Q9KmDp8opFfiEvGBVCUKaa9JiIJwXkhIQ0h9g0KCCd51DPF6ve87M/cDynpnzjHDGhtvyPlJKzGHZ2eemdnjmf9zznMexTRNE4IgTIs63x0QhGpHnEQQHBAnEQQHxEkEwQFxEkFwQJxEEBwQJxEEB8RJBMEBcRJBcECcRBAccM/Vjvv7+/H73/8esVgMK1euxFNPPYU1a9Y4fs8wDJw/fx6hUAiKosxV94QvOaZpIplMoqWlBarq8Kww54B9+/aZXq/X/POf/2y+99575k9+8hMzEomY8Xjc8bvDw8MmAPnI55p8hoeHHX+TimnOfoLj2rVrsXr1avzpT38CcOnp0NbWhq1bt+LnP//5Zb+bSCQQiUTwzjvvIBQKlezFYpG0rdYnzTXpl/2uMXeRu7Em80fTZFqqfEOKYlg3bduXvkavh8K86c/0p3il17t8/8lkErfffjvGx8ehadplvzfrr1v5fB7Hjx9Hb29vyaaqKrq6unDs2DHSPpfLIZfLlbaTySQAIBQKiZNcDnGSsmNW7iSVfHfWhfvY2Bh0XUc0GrXYo9EoYrEYad/X1wdN00qftra22e6SIFwV8z661dvbi0QiUfoMDw/Pd5cEwcKsv241NjbC5XIhHo9b7PF4HM3NzaS9z+eDz+cjdlVV4XK5Zrt714T5eA1UDJ3Y2JcXlfbNYF6HYDLX3mRem1TrURTQ1y2+J/P7ulXJb2vWnyRerxerVq3CwMBAyWYYBgYGBtDZ2TnbhxOEOWdO4iQ7duzAli1b8I1vfANr1qzBk08+iVQqhR/96EdzcThBmFPmxEkeeOABfPrpp3j00UcRi8Vw22234dChQ0TMC8IXgTmJk1wNExMT0DQNH330EcLhcMmu6/Sdu1r54mkShutckySTSdx0001IJBKW3xnHnKWlXC2maVpOqsp8+bLMdl/ZH4H9GCbz42S/xglW+oPNFWhcyu3x0K/q1uO6lCs9d9Y155SZ/p7mfQhYEKodcRJBcECcRBAcqFpNoiiK5V28WvK0qkYb2S6HzvTLNOg1KxpUCxSKVPR/8OGHxBZtbiI2I5+3bC+oryNt/D6qZYx5uI4z/T3Jk0QQHBAnEQQHxEkEwQFxEkFwoGqF+5UEE6tFzNu5mklAFRzFsuXyeEkLnYmQZyZzxDaeSBFbfOwisQVCNcTWUDYxDgBUhf7d5SZYcZOzrhjb9Z3Jr0CEuyDMIuIkguCAOIkgOCBOIggOVK1wV1UFallaNxc9nk0YjTtNrjnFLgLVKxSFOiM5DSYi7nLRv2X5fMGy/emFCdJmIpUltkyORtdTaSrmVV+Qtsvkia02aL1IReaa0SEFor2virkewJEniSA4IE4iCA6IkwiCA+IkguBA1Qr3dCYLl7ssxdqgitDN1E4ybe1cbtqGsynMtFNOzKuG898VlYsBM+JyMkeFNReFD7jpbcrapteOMMJ99DNq42psFRi1nU5O0v0xUfhzn4xYtm9dfBNpc/ONrcTmMpk5+VwGAldu1X4K3OVmdlV+X9h7NA3yJBEEB8RJBMEBcRJBcECcRBAcqFrhnsjkoLunYrW1QZqmrbrp3GndsApaVmczms3FiXS2GNsV/F25wrT+2MgnxFZfX09sAT+NWeeyact20EfbNC9opF1jTj6VpgMINV66v3w2Q2wu1ZohMJmj0fsic+6KQn96/NQB7rtOLXhj+e7ZDItpkCeJIDggTiIIDoiTCIIDVatJ3OF6uENlBbMZLVBQmbq2in75bQA6U1xa5XQEV8vqClKD2SAkYyvm6fu7wgTZYNC6vBHbVNpCgemXi2q2YG2I2DhNorjowkoKI9x8AesxFOZEi8yUXq50MacjuOtmT89mKhTzOmWG06XlSSIIDoiTCIID4iSC4IA4iSA4ULXC/b//51n4/IHStsJkAXuYYGJtyG/ZXtTRTtqsXnErsbmZPxf2jGKAD3iZdnXJBM+KjPiuYwKHXp+f2LgAoNdrFdYNdUxGNKjNzQQJvUyWMTy0H9kiPYfxic+s24kEaZNMjBNbIU0Dk1zqbkNDhNgWL7JmGnu8XGCS2X35feJHBFjkSSIIDoiTCIID4iSC4EDFTvLKK6/g3nvvRUtLCxRFwXPPPWf5f9M08eijj2LhwoUIBALo6urCBx98MFv9FYRrTsXCPZVKYeXKlfjxj3+MTZs2kf//3e9+hz/+8Y945pln0NHRgV/96ldYv349Tp06Bb+fisHpyKZzMMpqbeUzNCrsYQRn0qYbg0wbfekSejyT1pRSGeHu8waIzS4S2VWnGDGv1S+gx+RqSDHZBnlbfS4XI8jBRLq5QLfBZBF89DFd6eqT0VFiu3jhgmU7k6GCXM9RwZ9nanjlcmlia22LElt7m3U6cA0j3LmiaeUDIJXE3it2kg0bNmDDhg3s/5mmiSeffBK//OUvcd999wEA/vKXvyAajeK5557D97///UoPJwjzzqxqkjNnziAWi6Grq6tk0zQNa9euxbFjx9jv5HI5TExMWD6CUE3MqpPEYjEAQDRqfURGo9HS/9np6+uDpmmlT1tb22x2SRCumnkf3ert7UUikSh9hoeH57tLgmBhViPuzc3NAIB4PI6FCxeW7PF4HLfddhv7HZ/PB5+PpmXf/73voaYsrTvHRGhrAlREKzZJFmBEHbfIEveaZxQLxOZx08EHd8BqM5m6XpkCFaqmQfumMiKdyyxw247h8XBTja9sAKHADDRkDXruNeFaYquLRCzbep5+z++i92n8Ao3Mn/vkI2Jb1LGI2Fyq9bpxAyUu5jxnurDYrD5JOjo60NzcjIGBgZJtYmICr732Gjo7O2fzUIJwzaj4STI5OYnTp0+Xts+cOYMTJ06gvr4e7e3t2LZtG379619j8eLFpSHglpYWbNy4cTb7LQjXjIqd5M0338S3vvWt0vaOHTsAAFu2bMGePXvws5/9DKlUCg899BDGx8fxzW9+E4cOHaooRiII1UTFTnL33XdfdtVYRVHw+OOP4/HHH7+qjglCtVC1qfJGwYBRmFLYLkY+MTPcUeu1zv0O+OmgQCZLRXq6QOeWf/ThR8TmZSLu7R1fsWyfGT5P2hw8NEBsBZUKcj9TPyvInEONbbBAC4dJm4hG57N//esriG1BYx2x3dx6A7GpClN83BbVz2fpvH23Sn9mmSY6TaBlYYTablhIbLpuvVfpNDPIwA3qlHXVZM5lOuZ9CFgQqh1xEkFwQJxEEBwQJxEEB6pWuB984bBljrtRoOJMBbNkste6tHKIEbQ3LqYrLy1ooNHkhoV0fnx9YxOx+WusInr8/Y9Jm5Pv03SbDDNKyATr4WYSu0O2Yy5q/wpp07nmdmJrqKFivsbFzBFnMvbzeZryXtStQj3NzWfX6b0LBGlIIBKhRdHjsTixjdlW3ArUUJEebab3KRicGgBJZugAw3TIk0QQHBAnEQQHxEkEwYGq1SRv//N9uD1TgTW/h1lUJkeDgh6v1e/X3rGatPn4E6oPLowQE5YvW0Zs3gB9l07nrNrIwwT/vn47DeJlmfdir4feksU3dRDbsqW3WLZbGiOkTThI39WNLNVxw7FPiW30s8+IbWSMtktNpizb4+PjpE2+QM+Tq5XF1RzTmZWBC7aVh4MRqrOWg947rSy4mpqkqwtPhzxJBMEBcRJBcECcRBAcECcRBAeqVriPnT8LV9lKTfV1NFP1hlYaMLp1xWLLtsdHo2LvnXid2KLMfJdaZpWs0TGq8GvCmmW7IUz39b3v3kVsKlMXS9M0YmtsaCC2ixet9a7OfEwLACbG6cDGRCJJbMkJWu9qPJUitosTdMpt0Rbk9XhoZrPXR22qizn3ML1XEdv0YACoa7IKdV8wSNp4A9Q2WVa7LcXUcZsOeZIIggPiJILggDiJIDggTiIIDlStcB85PQSlTNhOMDWf/v2eh4ntu9/9tmX7fw//nbRpYiK0TUGagRpwUyHpZ4p2RTVrpnFIo5nHfibrtchk93JR56JOjxkb+sSyfXaUZsvmmWWr3X56nqEQnUrb5KfCt8DU1LLj8VKR7mJEOmcLheh9CYepzWVbKnsyRQce4vExYstmp9pl0nRgYjrkSSIIDoiTCIID4iSC4IA4iSA4ULXCPZtOWYT711YuJ23WfXsdsTVErNHpO9cykW6mkHTIQ9Pbw7VU5Lq8TMFsWy0uk9m/wUw1Tnx2gdjCbtoPg6kwdtMt1uvR1PpV0ubiZzTiHmIi2AWd9lcxmcLdKu2HYVtxK5ulkezJFE1LNw2azTCZpu2GR2iGQzZjFeqFND2mvTYXAARrpq6tfR+XQ54kguCAOIkgOCBOIggOiJMIggNVK9xv/OrX4CqrB/XAf/4XaZPWaXR36LQ18mwoTFFqJnpfYApNXRyn4g8GFXy6bl2FS2GuqgE6zzs5QdPWXXEa1T7PLA2dy1nbGVlaE6uGySL48INzxHbm7FliU5jVteobacp+Pmc9r0SCptNfGKPRb5MR1qpKMwsUxmYvhh1hsgj8XKH0yan7xA0wTIc8SQTBAXESQXBAnEQQHKhaTXLff/yHpRZwXTOt3/vOSfp+nbdlquYN+k6rM8E50+AWCWJWtGUyd3Vblq7JtGEW1QWYdoUi7e/YBZrhWyxadRDz6o5IOEJs+TzVRhcvMBmxLnqNxsboe3yuYO1HkZkWq+dpINXF1N0K+mltNR+XQVy09i2f5bKTqeYJlNVPZmZOT4s8SQTBAXESQXBAnEQQHKjISfr6+rB69WqEQiE0NTVh48aNGBoasrTJZrPo7u5GQ0MDamtrsXnzZsTj9J1aEL4oVCTcjxw5gu7ubqxevRrFYhG/+MUvcM899+DUqVOoqbkU0Nm+fTuef/557N+/H5qmoaenB5s2bcLRo0cr6tg7774NT1mR7H++e4K0UUALQpfX6gIAN5Pd63Jza8pz006peHV76d8V+xr1fO0p2g+VWcnXZdLvhr205pjqswZECy4qVLM6s+gOs7q4l6lbVUhTgZ9O0azifNHaTmEWW+JGLfJM5rHOTMNNJWk/gjbRv0CjwWE3M126fGaxQS/NtFTkJIcOHbJs79mzB01NTTh+/DjuuusuJBIJ7Nq1C3v37sW6dZfS2Hfv3o2lS5dicHAQd9xxRyWHE4Sq4Ko0yecpCPX1lwoJHD9+HIVCAV1dXaU2S5YsQXt7O44dO8buI5fLYWJiwvIRhGpixk5iGAa2bduGO++8E8uXX5oAFIvF4PV6SWnKaDSKWCzG7qevrw+appU+bW1tM+2SIMwJM3aS7u5unDx5Evv27buqDvT29iKRSJQ+w8N0gR1BmE9mFHHv6enBwYMH8corr6C1dSoS3tzcjHw+j/HxccvTJB6Po7m5md2Xz+eDjxG1g0dfglI2XTQ9MU7aeD1UcAaC9jpN9BRdJrPaLPP3QvVwwp2pxWWrlcVloHqZOlbuIM2q9XtpwWyvSsW829Zdxc9kByhMRD9Ho985JkpeKNB2BlNzDLZjcCsFg5n2C6aItlbD2ei9qg1YI/M+D+2XR6EDCErZSsGKPker75qmiZ6eHhw4cACHDx9GR4d1mbJVq1bB4/FgYGCgZBsaGsLZs2fR2dlZyaEEoWqo6EnS3d2NvXv34q9//StCoVBJZ2iahkAgAE3T8OCDD2LHjh2or69HOBzG1q1b0dnZKSNbwheWipxk586dAIC7777bYt+9ezd++MMfAgCeeOIJqKqKzZs3I5fLYf369Xj66adnpbOCMB9U5CSmybxv2vD7/ejv70d/f/+MOyUI1UTVpso3NYaglk3fHcnQ5ZF1fZzYwvXW4s9uZvruxBhdfjk5QdPFCzojXotU8JlMOj6BEd/eAF2py/TQYttFZj6walPuQSZ6X8Os9qQXmFCzwfzx81G5qnCDFrbod4AZtKhn6pe11tJC2K0LG4mNCZwjl7VOe1ZNOvDgdjGrZoWnrlGG3o5pkQRHQXBAnEQQHBAnEQQHxEkEwYGqFe5mIQPTmIrUajV0/nOSqZ1U0K1Fl29ZsozueyFd2enTMVq8evQCrRc1ydTiSqetKd46k6JuFGlfa9w0ur5kxc3Edp6pz/WpLQMhk6cDD5lshti4efs+D722NUy6f6SGDg4ssOXpNbfQzIpFN0SJrclHo/CTTCr+xYt0wMZlm64QrKFTCWpDtK8NDVPt0mk6wDAd8iQRBAfESQTBAXESQXCgajXJxdh5KMrU+7NeoO/0GSbjND1srWtb76Lv1o1M7VhPjk4dDTDFrDIuekzTtGsQpoYwk5GbzlDN82+rqYZatvRrxHb27MeW7QvjNECaYzJ+ucChm8nSDTALETUygcJIjfVa6sy5x8ZoreGhMbo4j8LU3Qo30UzpgG1F3mCI3k+ubnGtNqUBFfeV//TlSSIIDoiTCIID4iSC4IA4iSA4ULXCvSlaB1dZseRzZ2lx7GKOyWhVrLYz/zdEmiS8NDuW+2uRMugU0FSR2gwSPKSi16XQIJ49mxUA3jr6d2K7u4bWlVpuq2WV0WhWrVGkIlop0muWzdNBkQQzvZULrn78L2vhwbEMDQhmPfTcA000oFvXHCE2X5jeK5dt+m5Qo5nTPmYBI6Usq7z8307Ik0QQHBAnEQQHxEkEwQFxEkFwoGqFe+vNN8DtmereBJMhmjpHhSRsWa5c0eiLzGpSXmaKbJ5E0gHdZKLppvP0XYVZ3ZfR8jj9zzeIbThJBwsWqNYsV67+gM4Uqp5ksghizPTX00wGwjlm6nI6aL1uobaFpE204yvE5o9QsQ2V+TkyK13V1loHMoJhOmihMoXSzbLlrcwKlrqSJ4kgOCBOIggOiJMIggPiJILgQNUK91CkDp6ypYkWRGmNqhFGuNu1MFdSKsekcxeYdpxI13EFNbYYuGWrmZm0KGTolNvUGJ3Cqvoilm1Xjorv88x5ngAV36fd9JxStXSKQU0rnSa7oKXFst2wgE7V9dXQqHmeuR4mMwDic9M0fpfNxq1I5mJS4dWydipXxHsa5EkiCA6IkwiCA+IkguCAOIkgOFC1wt3vD8LrnUqJ9jHzqz3MctF6wSr+mEA3isx8c3CCnGvG7fAKqu0bTHjdZGyTTPHtf+Vp9FuzFcj+VzZO2rxXpLW4LjKp5/VtHcS28MYWYosw9cp8tjR+1aDnVGAEuctN57O7mCi520vbKar1GLrOTAlgrq1aFmVXuXSHaZAniSA4IE4iCA6IkwiCA+IkguBA1Qr3oq5DKUtzT2XofPBQhC6DlE1ZI8o6I4R1Jk1a57Q3Y1SYTHk2dG7DZAS/ycyzTqk0Pf/VfILYPk5b210M0nNyR9uIrfmGBcTWsYCuMNWg0eJuKjPXPmUb3cgygyJuJmrOLePtZ+alu730HvttK3j5/LSNhyn4PVPkSSIIDoiTCIIDFTnJzp07sWLFCoTDYYTDYXR2duKFF14o/X82m0V3dzcaGhpQW1uLzZs3Ix6n4/eC8EWiIk3S2tqK3/72t1i8eDFM08QzzzyD++67D2+//TaWLVuG7du34/nnn8f+/fuhaRp6enqwadMmHD16tOKOFfQcoE/pCZeXvuvWLaDvsIVaa/CpWKCahDGhwGgXk9EkzOxXKDZNwgWyuMAh3PS92e1mgnEBGlDLadbA3k0azZKuq6dTZGvD9JbXBqlm8PlpuyxTxytvyzQ2GS3g8jA/M+56MDYPE0y0ZwF7mP1zmcHlmdjO4d8pKnKSe++917L9m9/8Bjt37sTg4CBaW1uxa9cu7N27F+vWrQMA7N69G0uXLsXg4CDuuOOOSg4lCFXDjDWJruvYt28fUqkUOjs7cfz4cRQKBXR1dZXaLFmyBO3t7Th27Ni0+8nlcpiYmLB8BKGaqNhJ3n33XdTW1sLn8+Hhhx/GgQMHcOuttyIWi8Hr9SJiW0MvGo0iFotNu7++vj5omlb6tLXRYUtBmE8qdpJbbrkFJ06cwGuvvYZHHnkEW7ZswalTp2bcgd7eXiQSidJneHh4xvsShLmg4mCi1+vFokWLAACrVq3CG2+8gT/84Q944IEHkM/nMT4+bnmaxONxNDfTFVk/x+fzweejgSWXR4GrrNBypJ4GsmqZAJqet0oyTrgXdUakMwFBlakDpTB/V+wZpdzUUNXNBPs8VD4GmMBbiFnJKVprXbm31kdXm63xUpvXR4V1nom7TTIZ1hmmhpk9MOtnBiO8TNCUE+QqI7YVpnaYvcZYPk/rknm9jM0ztX+uTtl0XHWcxDAM5HI5rFq1Ch6PBwMDA6X/GxoawtmzZ9HZ2Xm1hxGEeaOiJ0lvby82bNiA9vZ2JJNJ7N27Fy+//DJefPFFaJqGBx98EDt27EB9fT3C4TC2bt2Kzs5OGdkSvtBU5CSjo6P4wQ9+gJGREWiahhUrVuDFF1/Ed77zHQDAE088AVVVsXnzZuRyOaxfvx5PP/30nHRcEK4VFTnJrl27Lvv/fr8f/f396O/vn3GHPn9XLNjeM4sFGsgqMsEtvWhedhvgkx45TWIazIw3rhSOTZOYzEuswZYUojZmWSIUCtRqfw/PMbWM3aDv+Fw/uOAqTLq/HBNcLdo0iWIwGoL5HleLl5GKMBWm9I89WVShOkhl9l/wTN3PdOrSrM0r0SaKWYmCuQacO3dOhoGFa8bw8DBaW1sv26bqnMQwDJw/fx6hUAjJZBJtbW0YHh5GOMxUIRfmlImJiev2+pumiWQyiZaWFqjMCFo5VTefRFXVkmd/ngP1eUKlMD9cr9df0zTnRpBUeUFwRJxEEByoaifx+Xx47LHH2Ii8MPfI9b9E1Ql3Qag2qvpJIgjVgDiJIDggTiIIDoiTCIID4iSC4EDVOkl/fz9uvPFG+P1+rF27Fq+//vp8d+m6pK+vD6tXr0YoFEJTUxM2btyIoaEhS5sve6moqnSSZ599Fjt27MBjjz2Gt956CytXrsT69esxOjo631277jhy5Ai6u7sxODiIf/zjHygUCrjnnnuQSk2tbbJ9+3b87W9/w/79+3HkyBGcP38emzZtmsdeX2PMKmTNmjVmd3d3aVvXdbOlpcXs6+ubx159ORgdHTUBmEeOHDFN0zTHx8dNj8dj7t+/v9Tm/fffNwGYx44dm69uXlOq7kmSz+dx/PhxS2kiVVXR1dV12dJEwuyQSFwqzl1ff6n43UxLRV1PVJ2TjI2NQdd1RKPW9cCdShMJV49hGNi2bRvuvPNOLF++HABmXCrqeqLqUuWF+aO7uxsnT57Eq6++Ot9dqSqq7knS2NgIl8tFRk+cShMJV0dPTw8OHjyIl156yTJTr7m5uVQqqpwv0/2oOifxer1YtWqVpTSRYRgYGBiQ0kRzgGma6OnpwYEDB3D48GF0dFhX4pVSUajO0a19+/aZPp/P3LNnj3nq1CnzoYceMiORiBmLxea7a9cdjzzyiKlpmvnyyy+bIyMjpU86nS61efjhh8329nbz8OHD5ptvvml2dnaanZ2d89jra0tVOolpmuZTTz1ltre3m16v11yzZo05ODg43126LsGlVQjIZ/fu3aU2mUzG/OlPf2rW1dWZwWDQvP/++82RkZH56/Q1RuaTCIIDVadJBKHaECcRBAfESQTBAXESQXBAnEQQHBAnEQQHxEkEwQFxEkFwQJxEEBwQJxEEB8RJBMGB/wckadMKp3LitgAAAABJRU5ErkJggg==",
      "text/plain": [
       "<Figure size 1500x200 with 1 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "plt.figure(figsize = (15,2))\n",
    "plt.imshow(X_test[1])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 53,
   "id": "0e2d92c4",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[[0.23137255, 0.24313725, 0.24705882],\n",
       "        [0.16862745, 0.18039216, 0.17647059],\n",
       "        [0.19607843, 0.18823529, 0.16862745],\n",
       "        ...,\n",
       "        [0.61960784, 0.51764706, 0.42352941],\n",
       "        [0.59607843, 0.49019608, 0.4       ],\n",
       "        [0.58039216, 0.48627451, 0.40392157]],\n",
       "\n",
       "       [[0.0627451 , 0.07843137, 0.07843137],\n",
       "        [0.        , 0.        , 0.        ],\n",
       "        [0.07058824, 0.03137255, 0.        ],\n",
       "        ...,\n",
       "        [0.48235294, 0.34509804, 0.21568627],\n",
       "        [0.46666667, 0.3254902 , 0.19607843],\n",
       "        [0.47843137, 0.34117647, 0.22352941]],\n",
       "\n",
       "       [[0.09803922, 0.09411765, 0.08235294],\n",
       "        [0.0627451 , 0.02745098, 0.        ],\n",
       "        [0.19215686, 0.10588235, 0.03137255],\n",
       "        ...,\n",
       "        [0.4627451 , 0.32941176, 0.19607843],\n",
       "        [0.47058824, 0.32941176, 0.19607843],\n",
       "        [0.42745098, 0.28627451, 0.16470588]],\n",
       "\n",
       "       ...,\n",
       "\n",
       "       [[0.81568627, 0.66666667, 0.37647059],\n",
       "        [0.78823529, 0.6       , 0.13333333],\n",
       "        [0.77647059, 0.63137255, 0.10196078],\n",
       "        ...,\n",
       "        [0.62745098, 0.52156863, 0.2745098 ],\n",
       "        [0.21960784, 0.12156863, 0.02745098],\n",
       "        [0.20784314, 0.13333333, 0.07843137]],\n",
       "\n",
       "       [[0.70588235, 0.54509804, 0.37647059],\n",
       "        [0.67843137, 0.48235294, 0.16470588],\n",
       "        [0.72941176, 0.56470588, 0.11764706],\n",
       "        ...,\n",
       "        [0.72156863, 0.58039216, 0.36862745],\n",
       "        [0.38039216, 0.24313725, 0.13333333],\n",
       "        [0.3254902 , 0.20784314, 0.13333333]],\n",
       "\n",
       "       [[0.69411765, 0.56470588, 0.45490196],\n",
       "        [0.65882353, 0.50588235, 0.36862745],\n",
       "        [0.70196078, 0.55686275, 0.34117647],\n",
       "        ...,\n",
       "        [0.84705882, 0.72156863, 0.54901961],\n",
       "        [0.59215686, 0.4627451 , 0.32941176],\n",
       "        [0.48235294, 0.36078431, 0.28235294]]])"
      ]
     },
     "execution_count": 53,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Normalize the dataset\n",
    "X_train = X_train / 255\n",
    "X_test = y_test / 255\n",
    "X_train[0]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 54,
   "id": "f3dc913c",
   "metadata": {},
   "outputs": [],
   "source": [
    "#CNN\n",
    "cnn = models.Sequential([\n",
    "    layers.Conv2D(filters = 32, kernel_size = (3,3), activation = 'relu'), \n",
    "    layers.MaxPooling2D((2,2)),\n",
    "    layers.Conv2D(filters = 16, kernel_size = (3,3), activation = 'relu'),\n",
    "    layers.MaxPooling2D((2,2)),\n",
    "    layers.Flatten(),\n",
    "    layers.Dense(64, activation = \"relu\"),\n",
    "    layers.Dense(10, activation = 'softmax')\n",
    "\n",
    "])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 55,
   "id": "43168b7f",
   "metadata": {},
   "outputs": [],
   "source": [
    "cnn.compile(optimizer='SGD',\n",
    "           loss = 'sparse_categorical_crossentropy',\n",
    "            metrics=['accuracy'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 56,
   "id": "c87dc41c",
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/10\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-03-08 23:38:13.714758: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.\n",
      "2023-03-08 23:38:13.791304: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:418 : NOT_FOUND: could not find registered platform with id: 0x11d87b420\n",
      "2023-03-08 23:38:13.791330: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:418 : NOT_FOUND: could not find registered platform with id: 0x11d87b420\n",
      "2023-03-08 23:38:13.794335: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:418 : NOT_FOUND: could not find registered platform with id: 0x11d87b420\n",
      "2023-03-08 23:38:13.794351: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:418 : NOT_FOUND: could not find registered platform with id: 0x11d87b420\n",
      "2023-03-08 23:38:13.802954: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:418 : NOT_FOUND: could not find registered platform with id: 0x11d87b420\n",
      "2023-03-08 23:38:13.802978: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:418 : NOT_FOUND: could not find registered platform with id: 0x11d87b420\n",
      "2023-03-08 23:38:13.807710: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:418 : NOT_FOUND: could not find registered platform with id: 0x11d87b420\n",
      "2023-03-08 23:38:13.807726: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:418 : NOT_FOUND: could not find registered platform with id: 0x11d87b420\n"
     ]
    },
    {
     "ename": "NotFoundError",
     "evalue": "Graph execution error:\n\nDetected at node 'StatefulPartitionedCall_6' defined at (most recent call last):\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/runpy.py\", line 194, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n      app.start()\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/ipykernel/kernelapp.py\", line 725, in start\n      self.io_loop.start()\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/tornado/platform/asyncio.py\", line 215, in start\n      self.asyncio_loop.run_forever()\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/asyncio/base_events.py\", line 570, in run_forever\n      self._run_once()\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/asyncio/base_events.py\", line 1859, in _run_once\n      handle._run()\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/asyncio/events.py\", line 81, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 513, in dispatch_queue\n      await self.process_one()\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 502, in process_one\n      await dispatch(*args)\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 409, in dispatch_shell\n      await result\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 729, in execute_request\n      reply_content = await reply_content\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n      res = shell.run_cell(\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/ipykernel/zmqshell.py\", line 540, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2961, in run_cell\n      result = self._run_cell(\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3016, in _run_cell\n      result = runner(coro)\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3221, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3400, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3460, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/var/folders/76/pgpg1wqx1vjdlv7_ccm6_rs00000gn/T/ipykernel_3002/366738251.py\", line 1, in <module>\n      cnn.fit(X_train, y_train, epochs=10)\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n      except Exception as e:  # pylint: disable=broad-except\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/engine/training.py\", line 1650, in fit\n      `ParameterServerStrategy`. Note that the progress bar is not\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/engine/training.py\", line 1249, in train_function\n      `tf.data` dataset, and 'steps_per_epoch'\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/engine/training.py\", line 1233, in step_function\n      you can pass a 2D array with shape\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/engine/training.py\", line 1222, in run_step\n      to a weight (float) value, used for weighting the loss function\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/engine/training.py\", line 1027, in train_step\n      \"\"\"Runs a single training step.\"\"\"\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 527, in minimize\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 1140, in apply_gradients\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 634, in apply_gradients\n      ...   initial_learning_rate=.01, decay_steps=20, decay_rate=.1)\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 1166, in _internal_apply_gradients\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 1216, in _distributed_apply_gradients_fn\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 1211, in apply_grad_to_update_var\nNode: 'StatefulPartitionedCall_6'\ncould not find registered platform with id: 0x11d87b420\n\t [[{{node StatefulPartitionedCall_6}}]] [Op:__inference_train_function_6649]",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNotFoundError\u001b[0m                             Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[56], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[43mcnn\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfit\u001b[49m\u001b[43m(\u001b[49m\u001b[43mX_train\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43my_train\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mepochs\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m10\u001b[39;49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/utils/traceback_utils.py:70\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     67\u001b[0m     filtered_tb \u001b[38;5;241m=\u001b[39m _process_traceback_frames(e\u001b[38;5;241m.\u001b[39m__traceback__)\n\u001b[1;32m     68\u001b[0m     \u001b[38;5;66;03m# To get the full stack trace, call:\u001b[39;00m\n\u001b[1;32m     69\u001b[0m     \u001b[38;5;66;03m# `tf.debugging.disable_traceback_filtering()`\u001b[39;00m\n\u001b[0;32m---> 70\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m e\u001b[38;5;241m.\u001b[39mwith_traceback(filtered_tb) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;28mNone\u001b[39m\n\u001b[1;32m     71\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[1;32m     72\u001b[0m     \u001b[38;5;28;01mdel\u001b[39;00m filtered_tb\n",
      "File \u001b[0;32m/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/tensorflow/python/eager/execute.py:52\u001b[0m, in \u001b[0;36mquick_execute\u001b[0;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[1;32m     50\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m     51\u001b[0m   ctx\u001b[38;5;241m.\u001b[39mensure_initialized()\n\u001b[0;32m---> 52\u001b[0m   tensors \u001b[38;5;241m=\u001b[39m pywrap_tfe\u001b[38;5;241m.\u001b[39mTFE_Py_Execute(ctx\u001b[38;5;241m.\u001b[39m_handle, device_name, op_name,\n\u001b[1;32m     53\u001b[0m                                       inputs, attrs, num_outputs)\n\u001b[1;32m     54\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m core\u001b[38;5;241m.\u001b[39m_NotOkStatusException \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m     55\u001b[0m   \u001b[38;5;28;01mif\u001b[39;00m name \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[0;31mNotFoundError\u001b[0m: Graph execution error:\n\nDetected at node 'StatefulPartitionedCall_6' defined at (most recent call last):\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/runpy.py\", line 194, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n      app.start()\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/ipykernel/kernelapp.py\", line 725, in start\n      self.io_loop.start()\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/tornado/platform/asyncio.py\", line 215, in start\n      self.asyncio_loop.run_forever()\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/asyncio/base_events.py\", line 570, in run_forever\n      self._run_once()\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/asyncio/base_events.py\", line 1859, in _run_once\n      handle._run()\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/asyncio/events.py\", line 81, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 513, in dispatch_queue\n      await self.process_one()\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 502, in process_one\n      await dispatch(*args)\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 409, in dispatch_shell\n      await result\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 729, in execute_request\n      reply_content = await reply_content\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n      res = shell.run_cell(\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/ipykernel/zmqshell.py\", line 540, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2961, in run_cell\n      result = self._run_cell(\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3016, in _run_cell\n      result = runner(coro)\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3221, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3400, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3460, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/var/folders/76/pgpg1wqx1vjdlv7_ccm6_rs00000gn/T/ipykernel_3002/366738251.py\", line 1, in <module>\n      cnn.fit(X_train, y_train, epochs=10)\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n      except Exception as e:  # pylint: disable=broad-except\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/engine/training.py\", line 1650, in fit\n      `ParameterServerStrategy`. Note that the progress bar is not\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/engine/training.py\", line 1249, in train_function\n      `tf.data` dataset, and 'steps_per_epoch'\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/engine/training.py\", line 1233, in step_function\n      you can pass a 2D array with shape\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/engine/training.py\", line 1222, in run_step\n      to a weight (float) value, used for weighting the loss function\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/engine/training.py\", line 1027, in train_step\n      \"\"\"Runs a single training step.\"\"\"\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 527, in minimize\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 1140, in apply_gradients\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 634, in apply_gradients\n      ...   initial_learning_rate=.01, decay_steps=20, decay_rate=.1)\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 1166, in _internal_apply_gradients\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 1216, in _distributed_apply_gradients_fn\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 1211, in apply_grad_to_update_var\nNode: 'StatefulPartitionedCall_6'\ncould not find registered platform with id: 0x11d87b420\n\t [[{{node StatefulPartitionedCall_6}}]] [Op:__inference_train_function_6649]"
     ]
    }
   ],
   "source": [
    "cnn.fit(X_train, y_train, epochs=10)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "id": "5fe8d6e9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/5\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-03-08 23:32:13.569680: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.\n",
      "2023-03-08 23:32:13.885611: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:418 : NOT_FOUND: could not find registered platform with id: 0x11d87b420\n",
      "2023-03-08 23:32:13.885636: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:418 : NOT_FOUND: could not find registered platform with id: 0x11d87b420\n",
      "2023-03-08 23:32:14.023687: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:418 : NOT_FOUND: could not find registered platform with id: 0x11d87b420\n",
      "2023-03-08 23:32:14.025697: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:418 : NOT_FOUND: could not find registered platform with id: 0x11d87b420\n",
      "2023-03-08 23:32:14.028734: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:418 : NOT_FOUND: could not find registered platform with id: 0x11d87b420\n",
      "2023-03-08 23:32:14.028746: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:418 : NOT_FOUND: could not find registered platform with id: 0x11d87b420\n"
     ]
    },
    {
     "ename": "NotFoundError",
     "evalue": "Graph execution error:\n\nDetected at node 'StatefulPartitionedCall_4' defined at (most recent call last):\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/runpy.py\", line 194, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n      app.start()\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/ipykernel/kernelapp.py\", line 725, in start\n      self.io_loop.start()\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/tornado/platform/asyncio.py\", line 215, in start\n      self.asyncio_loop.run_forever()\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/asyncio/base_events.py\", line 570, in run_forever\n      self._run_once()\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/asyncio/base_events.py\", line 1859, in _run_once\n      handle._run()\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/asyncio/events.py\", line 81, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 513, in dispatch_queue\n      await self.process_one()\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 502, in process_one\n      await dispatch(*args)\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 409, in dispatch_shell\n      await result\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 729, in execute_request\n      reply_content = await reply_content\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n      res = shell.run_cell(\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/ipykernel/zmqshell.py\", line 540, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2961, in run_cell\n      result = self._run_cell(\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3016, in _run_cell\n      result = runner(coro)\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3221, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3400, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3460, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/var/folders/76/pgpg1wqx1vjdlv7_ccm6_rs00000gn/T/ipykernel_3002/2409442702.py\", line 12, in <module>\n      ann.fit(X_train, y_train, epochs=5)\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n      except Exception as e:  # pylint: disable=broad-except\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/engine/training.py\", line 1650, in fit\n      `ParameterServerStrategy`. Note that the progress bar is not\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/engine/training.py\", line 1249, in train_function\n      `tf.data` dataset, and 'steps_per_epoch'\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/engine/training.py\", line 1233, in step_function\n      you can pass a 2D array with shape\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/engine/training.py\", line 1222, in run_step\n      to a weight (float) value, used for weighting the loss function\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/engine/training.py\", line 1027, in train_step\n      \"\"\"Runs a single training step.\"\"\"\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 527, in minimize\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 1140, in apply_gradients\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 634, in apply_gradients\n      ...   initial_learning_rate=.01, decay_steps=20, decay_rate=.1)\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 1166, in _internal_apply_gradients\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 1216, in _distributed_apply_gradients_fn\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 1211, in apply_grad_to_update_var\nNode: 'StatefulPartitionedCall_4'\ncould not find registered platform with id: 0x11d87b420\n\t [[{{node StatefulPartitionedCall_4}}]] [Op:__inference_train_function_4212]",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNotFoundError\u001b[0m                             Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[38], line 12\u001b[0m\n\u001b[1;32m      1\u001b[0m ann \u001b[38;5;241m=\u001b[39m models\u001b[38;5;241m.\u001b[39mSequential([\n\u001b[1;32m      2\u001b[0m         layers\u001b[38;5;241m.\u001b[39mFlatten(input_shape\u001b[38;5;241m=\u001b[39m(\u001b[38;5;241m32\u001b[39m,\u001b[38;5;241m32\u001b[39m,\u001b[38;5;241m3\u001b[39m)),\n\u001b[1;32m      3\u001b[0m         layers\u001b[38;5;241m.\u001b[39mDense(\u001b[38;5;241m3000\u001b[39m, activation\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mrelu\u001b[39m\u001b[38;5;124m'\u001b[39m),\n\u001b[1;32m      4\u001b[0m         layers\u001b[38;5;241m.\u001b[39mDense(\u001b[38;5;241m1000\u001b[39m, activation\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mrelu\u001b[39m\u001b[38;5;124m'\u001b[39m),\n\u001b[1;32m      5\u001b[0m         layers\u001b[38;5;241m.\u001b[39mDense(\u001b[38;5;241m10\u001b[39m, activation\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124msoftmax\u001b[39m\u001b[38;5;124m'\u001b[39m)    \n\u001b[1;32m      6\u001b[0m     ])\n\u001b[1;32m      8\u001b[0m ann\u001b[38;5;241m.\u001b[39mcompile(optimizer\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mSGD\u001b[39m\u001b[38;5;124m'\u001b[39m,\n\u001b[1;32m      9\u001b[0m               loss\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124msparse_categorical_crossentropy\u001b[39m\u001b[38;5;124m'\u001b[39m,\n\u001b[1;32m     10\u001b[0m               metrics\u001b[38;5;241m=\u001b[39m[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124maccuracy\u001b[39m\u001b[38;5;124m'\u001b[39m])\n\u001b[0;32m---> 12\u001b[0m \u001b[43mann\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfit\u001b[49m\u001b[43m(\u001b[49m\u001b[43mX_train\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43my_train\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mepochs\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m5\u001b[39;49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/utils/traceback_utils.py:70\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     67\u001b[0m     filtered_tb \u001b[38;5;241m=\u001b[39m _process_traceback_frames(e\u001b[38;5;241m.\u001b[39m__traceback__)\n\u001b[1;32m     68\u001b[0m     \u001b[38;5;66;03m# To get the full stack trace, call:\u001b[39;00m\n\u001b[1;32m     69\u001b[0m     \u001b[38;5;66;03m# `tf.debugging.disable_traceback_filtering()`\u001b[39;00m\n\u001b[0;32m---> 70\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m e\u001b[38;5;241m.\u001b[39mwith_traceback(filtered_tb) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;28mNone\u001b[39m\n\u001b[1;32m     71\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[1;32m     72\u001b[0m     \u001b[38;5;28;01mdel\u001b[39;00m filtered_tb\n",
      "File \u001b[0;32m/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/tensorflow/python/eager/execute.py:52\u001b[0m, in \u001b[0;36mquick_execute\u001b[0;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[1;32m     50\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m     51\u001b[0m   ctx\u001b[38;5;241m.\u001b[39mensure_initialized()\n\u001b[0;32m---> 52\u001b[0m   tensors \u001b[38;5;241m=\u001b[39m pywrap_tfe\u001b[38;5;241m.\u001b[39mTFE_Py_Execute(ctx\u001b[38;5;241m.\u001b[39m_handle, device_name, op_name,\n\u001b[1;32m     53\u001b[0m                                       inputs, attrs, num_outputs)\n\u001b[1;32m     54\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m core\u001b[38;5;241m.\u001b[39m_NotOkStatusException \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m     55\u001b[0m   \u001b[38;5;28;01mif\u001b[39;00m name \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[0;31mNotFoundError\u001b[0m: Graph execution error:\n\nDetected at node 'StatefulPartitionedCall_4' defined at (most recent call last):\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/runpy.py\", line 194, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n      app.start()\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/ipykernel/kernelapp.py\", line 725, in start\n      self.io_loop.start()\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/tornado/platform/asyncio.py\", line 215, in start\n      self.asyncio_loop.run_forever()\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/asyncio/base_events.py\", line 570, in run_forever\n      self._run_once()\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/asyncio/base_events.py\", line 1859, in _run_once\n      handle._run()\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/asyncio/events.py\", line 81, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 513, in dispatch_queue\n      await self.process_one()\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 502, in process_one\n      await dispatch(*args)\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 409, in dispatch_shell\n      await result\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 729, in execute_request\n      reply_content = await reply_content\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n      res = shell.run_cell(\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/ipykernel/zmqshell.py\", line 540, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2961, in run_cell\n      result = self._run_cell(\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3016, in _run_cell\n      result = runner(coro)\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3221, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3400, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3460, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/var/folders/76/pgpg1wqx1vjdlv7_ccm6_rs00000gn/T/ipykernel_3002/2409442702.py\", line 12, in <module>\n      ann.fit(X_train, y_train, epochs=5)\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n      except Exception as e:  # pylint: disable=broad-except\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/engine/training.py\", line 1650, in fit\n      `ParameterServerStrategy`. Note that the progress bar is not\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/engine/training.py\", line 1249, in train_function\n      `tf.data` dataset, and 'steps_per_epoch'\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/engine/training.py\", line 1233, in step_function\n      you can pass a 2D array with shape\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/engine/training.py\", line 1222, in run_step\n      to a weight (float) value, used for weighting the loss function\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/engine/training.py\", line 1027, in train_step\n      \"\"\"Runs a single training step.\"\"\"\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 527, in minimize\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 1140, in apply_gradients\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 634, in apply_gradients\n      ...   initial_learning_rate=.01, decay_steps=20, decay_rate=.1)\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 1166, in _internal_apply_gradients\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 1216, in _distributed_apply_gradients_fn\n    File \"/opt/anaconda3/envs/cifar10cnn/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 1211, in apply_grad_to_update_var\nNode: 'StatefulPartitionedCall_4'\ncould not find registered platform with id: 0x11d87b420\n\t [[{{node StatefulPartitionedCall_4}}]] [Op:__inference_train_function_4212]"
     ]
    }
   ],
   "source": [
    "ann = models.Sequential([\n",
    "        layers.Flatten(input_shape=(32,32,3)),\n",
    "        layers.Dense(3000, activation='relu'),\n",
    "        layers.Dense(1000, activation='relu'),\n",
    "        layers.Dense(10, activation='softmax')    \n",
    "    ])\n",
    "\n",
    "ann.compile(optimizer='SGD',\n",
    "              loss='sparse_categorical_crossentropy',\n",
    "              metrics=['accuracy'])\n",
    "\n",
    "ann.fit(X_train, y_train, epochs=5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "30470db6",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
